# docker-compose.yml

version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask-backend-bab
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:admin@postgres/Chatbot2

    volumes:
      - .:/app
    depends_on:
      - frontend
      - postgres # Add this dependency

  frontend:
    build:
      context: ./app_react
      dockerfile: Dockerfile
    container_name: react-frontend-bab
    ports:
      - "3000:80"
    volumes:
      - ./app_react:/app
      - /app/node_modules

  postgres:
    image: postgres:13 # Using the official PostgreSQL image
    container_name: flask-postgres-bab
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Chatbot2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data

volumes:
  postgres-data:
